# -*- coding: utf-8 -*-
"""fish_classification_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwJEdlnGNwZOia7LuUA5W5vXAazCtT4j

# Fish Species Classification — IoT Pond Water Data
### Improved Pipeline over Islam et al. (2023)

**Key improvements over base paper:**
- Removes 99.3% duplicate rows (data leakage fix)
- IoT sensor-realistic Gaussian noise augmentation (400 samples/class)
- Domain-specific derived features: DO, Ammonia, Nitrite, BOD
- Polynomial + interaction features
- Honest stratified 5-fold CV evaluation
- Ensemble model (RF + ExtraTrees)
- Single best-prediction output per water reading

## 1. Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import (
    RandomForestClassifier, ExtraTreesClassifier,
    GradientBoostingClassifier, VotingClassifier
)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)

np.random.seed(42)
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.size']  = 11
print('All imports successful')

"""## 2. Load & Explore Raw Data"""

df_raw = pd.read_csv('/content/fish_dataset_clean_augmented.csv')
# df_raw = pd.read_csv('/fish_dataset_clean_augmented.csv')
print(f'Raw shape: {df_raw.shape}')
print(f'Columns  : {df_raw.columns.tolist()}')
df_raw.head(10)

print('=== Class Distribution (Raw) ===')
print(df_raw['fish'].value_counts())
print(f'\nTotal rows     : {len(df_raw):,}')
print(f'Duplicate rows : {df_raw.duplicated().sum():,} ({df_raw.duplicated().sum()/len(df_raw)*100:.1f}%)')
print(f'Unique rows    : {df_raw.drop_duplicates().shape[0]}')

# Visualise duplicate problem
df_u = df_raw.drop_duplicates()
dup_data = {'Species': [], 'Total': [], 'Unique': []}
for fish in df_raw['fish'].unique():
    dup_data['Species'].append(fish)
    dup_data['Total'].append(len(df_raw[df_raw['fish']==fish]))
    dup_data['Unique'].append(len(df_u[df_u['fish']==fish]))

dup_df = pd.DataFrame(dup_data).sort_values('Total', ascending=False)

fig, ax = plt.subplots(figsize=(12, 4))
x = np.arange(len(dup_df))
ax.bar(x, dup_df['Total'],  label='Total (with duplicates)', color='#c0392b', alpha=0.7)
ax.bar(x, dup_df['Unique'], label='Unique rows only',        color='#27ae60')
ax.set_xticks(x); ax.set_xticklabels(dup_df['Species'], rotation=30, ha='right')
ax.set_ylabel('Row count'); ax.set_title('Data Leakage: Total vs Unique Rows per Species')
ax.legend()
plt.tight_layout(); plt.show()

"""## 3. Deduplication + IoT-Noise Augmentation"""

# Step 1: Remove duplicates
df_unique = df_raw.drop_duplicates().reset_index(drop=True)
print(f'Unique rows: {len(df_unique)} across {df_unique["fish"].nunique()} species')
print(df_unique['fish'].value_counts())

# Step 2: Augment with IoT sensor-realistic Gaussian noise
# Noise based on actual sensor datasheets:
#   pH sensor       : ±0.05 accuracy
#   DS18B20 temp    : ±0.30 °C
#   Turbidity sensor: ±0.15 NTU

TARGET_PER_CLASS = 400
PH_NOISE   = 0.05
TEMP_NOISE = 0.30
TURB_NOISE = 0.15

frames = []
for fish, grp in df_unique.groupby('fish'):
    frames.append(grp)
    need = TARGET_PER_CLASS - len(grp)
    rows = []
    for i in range(need):
        base = grp.sample(1, replace=True, random_state=i).iloc[0]
        rows.append({
            'ph':          round(float(np.clip(base['ph']          + np.random.normal(0, PH_NOISE),   5.0, 9.5)),  2),
            'temperature': round(float(np.clip(base['temperature'] + np.random.normal(0, TEMP_NOISE), 4.0, 36.0)), 2),
            'turbidity':   round(float(np.clip(base['turbidity']   + np.random.normal(0, TURB_NOISE), 1.0, 16.0)), 2),
            'fish': fish
        })
    frames.append(pd.DataFrame(rows))

df = pd.concat(frames, ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
print(f'Augmented dataset: {df.shape}')
print(f'Class distribution:\n{df["fish"].value_counts()}')
print(f'Remaining duplicates: {df.duplicated().sum()}')

"""## 4. Feature Engineering"""

# ── 4a. Domain-Specific Derived Features ──────────────────────────────────
# Dissolved Oxygen (DO): decreases with temp and turbidity
df['DO']      = (8 - 0.1*df['temperature'] - 0.05*df['turbidity']).clip(3, 8)

# Ammonia: increases with turbidity (organic load) and temperature
# df['ammonia'] = (0.02*df['turbidity'] + 0.005*df['temperature']).clip(0.01, 0.1)

# Nitrite: by-product of ammonia oxidation
# df['nitrite'] = (df['ammonia'] * 0.8).clip(0.01, 0.05)

# Biological Oxygen Demand: inversely related to DO
df['BOD']     = (5 - df['DO']*0.5).clip(1, 6)

# ── 4b. Polynomial & Interaction Features ─────────────────────────────────
df['ph_sq']       = df['ph'] ** 2
df['temp_sq']     = df['temperature'] ** 2
df['turb_sq']     = df['turbidity'] ** 2
df['ph_temp']     = df['ph'] * df['temperature']
df['ph_turb']     = df['ph'] * df['turbidity']
df['temp_turb']   = df['temperature'] * df['turbidity']
# df['DO_ph']       = df['DO'] * df['ph']
# df['DO_temp']     = df['DO'] * df['temperature']
# df['ammonia_BOD'] = df['ammonia'] * df['BOD']

FEATURES = [c for c in df.columns if c != 'fish']
print(f'Total features: {len(FEATURES)}')
print(FEATURES)
df[FEATURES].describe().round(3)

# Correlation heatmap
fig, ax = plt.subplots(figsize=(14, 10))
corr = df[FEATURES].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, linewidths=0.5, ax=ax, annot_kws={'size': 7})
ax.set_title('Feature Correlation Matrix')
plt.tight_layout(); plt.show()

"""## 5. Encode & Split"""

le = LabelEncoder()
X = df[FEATURES]
y = le.fit_transform(df['fish'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f'Classes  : {list(le.classes_)}')
print(f'Train set: {X_train.shape[0]} rows')
print(f'Test set : {X_test.shape[0]} rows')

"""## 6. Model Comparison"""

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

model_zoo = {
    'Decision Tree':        DecisionTreeClassifier(random_state=42),
    'KNN (k=3)':            KNeighborsClassifier(n_neighbors=3),
    'KNN (k=5)':            KNeighborsClassifier(n_neighbors=5),
    'KNN (k=7)':            KNeighborsClassifier(n_neighbors=7),
    'Random Forest':        RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1),
    'Extra Trees':          ExtraTreesClassifier(n_estimators=200, random_state=42, n_jobs=-1),
    'Gradient Boosting':    GradientBoostingClassifier(n_estimators=100, random_state=42),
    'Ensemble (RF + ET)':   VotingClassifier([
                                ('rf', RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1)),
                                ('et', ExtraTreesClassifier(n_estimators=300, random_state=7, n_jobs=-1))
                            ], voting='soft'),
}

results = []
print(f"{'Model':<25} {'Test Acc':>10} {'CV Mean':>10} {'CV Std':>8}")
print('-' * 58)

for name, model in model_zoo.items():
    model.fit(X_train, y_train)
    test_acc = accuracy_score(y_test, model.predict(X_test))
    cv_sc    = cross_val_score(model, X, y, cv=skf, scoring='accuracy')
    results.append({'Model': name, 'Test Acc': test_acc,
                    'CV Mean': cv_sc.mean(), 'CV Std': cv_sc.std()})
    print(f"{name:<25} {test_acc*100:>9.2f}% {cv_sc.mean()*100:>9.2f}% {cv_sc.std()*100:>7.2f}%")

results_df = pd.DataFrame(results).sort_values('CV Mean', ascending=False)
print('-' * 58)
print(f"\nBest model: {results_df.iloc[0]['Model']}  →  CV {results_df.iloc[0]['CV Mean']*100:.2f}%")

# Bar chart comparison
fig, ax = plt.subplots(figsize=(12, 5))
models_sorted = results_df['Model'].tolist()
cv_means = results_df['CV Mean'].values * 100
cv_stds  = results_df['CV Std'].values  * 100
test_acc = results_df['Test Acc'].values * 100

x = np.arange(len(models_sorted))
bars1 = ax.bar(x - 0.2, cv_means,  0.35, label='CV Mean Acc', color='#2980b9', yerr=cv_stds, capsize=4)
bars2 = ax.bar(x + 0.2, test_acc,  0.35, label='Test Acc',    color='#27ae60')

ax.set_xticks(x)
ax.set_xticklabels(models_sorted, rotation=25, ha='right')
ax.set_ylabel('Accuracy (%)')
ax.set_title('Model Comparison: CV vs Test Accuracy')
ax.set_ylim(60, 100)
ax.legend()
ax.axhline(y=85, color='red', linestyle='--', alpha=0.5, label='85% baseline')

for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
            f'{bar.get_height():.1f}', ha='center', va='bottom', fontsize=8)
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
            f'{bar.get_height():.1f}', ha='center', va='bottom', fontsize=8)

plt.tight_layout(); plt.show()

"""## 7. Best Model — Detailed Evaluation"""

# Train best model (Ensemble RF + ExtraTrees)
best_model = VotingClassifier([
    ('rf', RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1)),
    ('et', ExtraTreesClassifier(n_estimators=300, random_state=7,  n_jobs=-1))
], voting='soft')

best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

print(f'Test Accuracy : {accuracy_score(y_test, y_pred)*100:.2f}%')
print()
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(11, 9))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
disp.plot(ax=ax, colorbar=True, cmap='Blues')
ax.set_title('Confusion Matrix — Best Model (ET)')
plt.xticks(rotation=30, ha='right')
plt.tight_layout(); plt.show()

# Per-species F1 bar chart
rpt = classification_report(y_test, y_pred, target_names=le.classes_, output_dict=True)
species_f1 = {cls: rpt[cls]['f1-score'] for cls in le.classes_}
sf1_sorted = dict(sorted(species_f1.items(), key=lambda x: -x[1]))

colors = ['#27ae60' if v >= 0.85 else '#f39c12' if v >= 0.70 else '#e74c3c'
          for v in sf1_sorted.values()]

fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.bar(sf1_sorted.keys(), [v*100 for v in sf1_sorted.values()], color=colors)
ax.set_ylabel('F1 Score (%)')
ax.set_title('Per-Species F1 Score')
ax.set_ylim(0, 105)
ax.axhline(85, color='gray', linestyle='--', alpha=0.6)
plt.xticks(rotation=30, ha='right')

for bar in bars:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
            f'{bar.get_height():.1f}', ha='center', va='bottom', fontsize=9)

patches = [
    mpatches.Patch(color='#27ae60', label='F1 ≥ 85%'),
    mpatches.Patch(color='#f39c12', label='70% ≤ F1 < 85%'),
    mpatches.Patch(color='#e74c3c', label='F1 < 70%'),
]
ax.legend(handles=patches, loc='lower right')
plt.tight_layout(); plt.show()

"""## 8. Feature Importance"""

# Average importance from both RF and ET estimators
rf_est = best_model.estimators_[0]
et_est = best_model.estimators_[1]
avg_imp = (rf_est.feature_importances_ + et_est.feature_importances_) / 2

fi_df = pd.Series(avg_imp, index=FEATURES).sort_values(ascending=True)

fig, ax = plt.subplots(figsize=(9, 7))
colors_fi = ['#e74c3c' if f in ['DO','ammonia','nitrite','BOD','ammonia_BOD','DO_ph','DO_temp']
             else '#2980b9' for f in fi_df.index]
bars = ax.barh(fi_df.index, fi_df.values * 100, color=colors_fi)
ax.set_xlabel('Importance (%)')
ax.set_title('Feature Importances (avg RF + ET)')

dom_patch = mpatches.Patch(color='#e74c3c', label='Domain-derived features')
raw_patch = mpatches.Patch(color='#2980b9', label='Raw / polynomial features')
ax.legend(handles=[dom_patch, raw_patch])

for bar in bars:
    ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
            f'{bar.get_width():.2f}%', va='center', fontsize=8)

plt.tight_layout(); plt.show()

print('\nTop 5 most important features:')
print(fi_df.sort_values(ascending=False).head(5).round(4).to_string())

"""## 9. Fish Species Prediction"""

def build_features(ph, temperature, turbidity):
    """Compute all 16 features from 3 raw sensor readings."""
    DO      = float(np.clip(8 - 0.1*temperature - 0.05*turbidity, 3, 8))
    ammonia = float(np.clip(0.02*turbidity + 0.005*temperature,   0.01, 0.1))
    nitrite = float(np.clip(ammonia * 0.8,                         0.01, 0.05))
    BOD     = float(np.clip(5 - DO*0.5,                            1, 6))
    return pd.DataFrame([{
        'ph': ph, 'temperature': temperature, 'turbidity': turbidity,
        'DO': DO,
        # 'ammonia': ammonia,
        # 'nitrite': nitrite,
        'BOD': BOD,
        'ph_sq':       ph**2,
        'temp_sq':     temperature**2,
        'turb_sq':     turbidity**2,
        'ph_temp':     ph * temperature,
        'ph_turb':     ph * turbidity,
        'temp_turb':   temperature * turbidity,
        # 'DO_ph':       DO * ph,
        # 'DO_temp':     DO * temperature,
        # 'ammonia_BOD': ammonia * BOD,
    }])[FEATURES]


def predict_fish(ph, temperature, turbidity):
    """
    Predict which fish species can survive in given water conditions.

    Parameters
    ----------
    ph          : float  — pH of the pond water
    temperature : float  — water temperature in °C
    turbidity   : float  — turbidity in NTU

    Returns
    -------
    Prints the predicted fish species.
    """
    X_input = build_features(ph, temperature, turbidity)
    species = le.classes_[best_model.predict(X_input)[0]]
    print(f"pH: {ph}  |  Temperature: {temperature}°C  |  Turbidity: {turbidity} NTU")
    print(f"Predicted Fish Species: {species}")

print("predict_fish() is ready.")

# ── Enter your sensor readings here ──────────────────────────────────────
ph          = 7.5   # pH value (e.g. 6.0 – 9.0)
temperature = 35.0  # Temperature in °C
turbidity   = 6.0   # Turbidity in NTU

predict_fish(ph, temperature, turbidity)

# ── Final summary ─────────────────────────────────────────────────────────
final_cv  = cross_val_score(best_model, X, y, cv=skf, scoring='accuracy')
final_acc = accuracy_score(y_test, y_pred)

print('=' * 50)
print('         FINAL RESULTS SUMMARY')
print('=' * 50)
print(f'  Dataset rows (clean, balanced) : {len(df):,}')
print(f'  Classes                        : {len(le.classes_)} fish species')
print(f'  Features                       : {len(FEATURES)}')
print(f'  Best model                     : Ensemble (RF + ExtraTrees)')
print(f'  Test Accuracy                  : {final_acc*100:.2f}%')
print(f'  5-Fold CV Accuracy             : {final_cv.mean()*100:.2f}% ± {final_cv.std()*100:.2f}%')
print(f'  CV Fold scores                 : {[round(s*100,2) for s in final_cv]}')
print('=' * 50)